### ISSUE TITLE
WTF?

### ISSUE THREAD

**Issue by Domosed-gamin** [rkulla/starmazer#1]
How can I beat this level? Here is very many stars. Bug?

https://imgur.com/a/0ZXkebt

**Comment by rkulla** [comment]
@Domosed-gamin You're the first person I've known that ever played it haha. I wrote this many moons ago as a noob and i'm sure it's buggy, has bad randomness, etc.  For that I apologize.  I don't have time to really look into it but I would accept a patch.  Hope it was fun at least.
